spring:
  application:
    name: "wolpi"
logging:
    level:
        org.apache: WARN
        org.springframework: WARN
        dev.mdz.wolpi: INFO
        org.springframework.web.servlet:
          PageNotFound: ERROR

server:
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      base-path: "/monitoring"
  endpoint:
    prometheus:
      access: read_only

wolpi:
  logging:
    level: info
    format: text
  # Location to store extensions installed from packagesin
  data-directory: "./data"
  # Fallback location where images are loaded from if no resolving
    # extension provides the image
  image-base-dir: "./images"
  # List of extensions to load
  extensions: []
  #extensions:
  #  # An extension in a single file with config
  #  - path: "./samples/helloworld.js"
  #    config:
  #      baseDirectory: "./images"
  #  # A local packaged extension
  #  - path: "./samples/hello-js-package"
  #  # An extension from npm
  #  - npm:
  #      pkg: "@my-org/hello-npm-package"
  #      version: "1.0.0"
  #  # An extension from a custom PyPI index
  #  - pypi:
  #      pkg: "hello-pypi-package"
  #      version: "0.1.0"
  #      index: "https://pypi.org.tld/simple/"
  extension-pool:
    max-total: 16
    max-idle: 4
  packaging:
    install-timeout: 180s

    # NPM executable, default: auto-discovered from PATH
    # npm-executable: "/usr/local/bin/npm"

    # Python executable, default: auto-discovered from PATH
    # Needs to be set to a GraalPython executable if using Python extensions
    # with native dependencies
    # python-executable: "/usr/local/bin/graalpy"

  # Extension Debugging via Debug Adapter Protocol
  extension-debug:
    # Enable or disable extension debugging, global setting for
    # all extensions and languages
    enabled: false
    # Host and port to listen on for debugger connections
    host: localhost
    port: 4711
    # Suspend execution at first source line
    suspend: false
    # Only begin executing after a debugger has connected
    waitAttached: false

  cache-control-headers:
    images: "public, max-age=604800, must-revalidate"
    info-json: "public, max-age=604800, must-revalidate"
  encoding-options:
    jpg:
      Q: 80
      optimize_coding: true
      interlace: false
      # overshoot_deringing: true # only available with mozjpeg
      # quant_table: 3 # mozjpeg default table
    tif:
      Q: 80
      compression: "VIPS_FOREIGN_TIFF_COMPRESSION_JPEG"
      tile: true
      tile_width: 512
      tile_height: 512
    webp:
      Q: 80
      preset: VIPS_FOREIGN_WEBP_PRESET_TEXT
      effort: 3
  iiif:
    restrict-to-sizes: false
    features:
      scaling:
        by-confined-width-height: true
        by-height: true
        by-width: true
        by-percent: true
        allow-upscaling: false
        by-arbitrary-dimensions: true
      region:
        by-percent: true
        by-pixels: true
        square: true
      rotation:
        mirroring: true
        by90-degree-rotation: true
        arbitrary: true
      profile-link-header: true
      json-ld-media-type: true
      cors: true
      canonical-link-header: true
      canonical-redirect: true
      base-uri-redirect: true
    qualities:
      allowed:
        - color
        - gray
        - bitonal
      default-quality: color
    formats:
      allowed:
        - jpg
        - tif
        - png
        - gif
        - jp2
        - webp
      preferred:
        - jpg
        - webp
        - png
    limits:
      max-width: 0
      max-height: 0
      max-area: 0